#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : suds-jurko
Version  : 0.6
Release  : 16
URL      : https://bitbucket.org/jurko/suds/downloads/suds-jurko-0.6.tar.bz2
Source0  : https://bitbucket.org/jurko/suds/downloads/suds-jurko-0.6.tar.bz2
Summary  : Lightweight SOAP client (Jurko's fork)
Group    : Development/Tools
License  : LGPL-3.0
Requires: suds-jurko-python
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python-dev
BuildRequires : python3-dev
BuildRequires : setuptools

%description
Overview
=================================================
"Suds" is a lightweight SOAP-based web service client for Python licensed under
LGPL (see the ``LICENSE.txt`` file included in the distribution).

%package python
Summary: python components for the suds-jurko package.
Group: Default

%description python
python components for the suds-jurko package.


%prep
%setup -q -n suds-jurko-0.6

%build
export LANG=C
export SOURCE_DATE_EPOCH=1491429687
python2 setup.py build -b py2
python3 setup.py build -b py3

%install
export SOURCE_DATE_EPOCH=1491429687
rm -rf %{buildroot}
python2 -tt setup.py build -b py2 install --root=%{buildroot} --force
python3 -tt setup.py build -b py3 install --root=%{buildroot} --force
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)
%exclude /usr/lib/python3.6/site-packages/tests/__init__.py
%exclude /usr/lib/python3.6/site-packages/tests/__pycache__/__init__.cpython-36.pyc
/usr/lib/python2*/*
/usr/lib/python3*/*
