#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : suds-jurko
Version  : 0.6
Release  : 22
URL      : https://bitbucket.org/jurko/suds/downloads/suds-jurko-0.6.tar.bz2
Source0  : https://bitbucket.org/jurko/suds/downloads/suds-jurko-0.6.tar.bz2
Summary  : Lightweight SOAP client (Jurko's fork)
Group    : Development/Tools
License  : LGPL-3.0
Requires: suds-jurko-python3
Requires: suds-jurko-license
Requires: suds-jurko-python
BuildRequires : buildreq-distutils3
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python3-dev
BuildRequires : setuptools

%description
---------------------------------------
        Lightweight SOAP client (Jurko's fork).
        ---------------------------------------
        
          Based on the original 'suds' project by Jeff Ortel (jortel at redhat

%package license
Summary: license components for the suds-jurko package.
Group: Default

%description license
license components for the suds-jurko package.


%package python
Summary: python components for the suds-jurko package.
Group: Default
Requires: suds-jurko-python3

%description python
python components for the suds-jurko package.


%package python3
Summary: python3 components for the suds-jurko package.
Group: Default
Requires: python3-core

%description python3
python3 components for the suds-jurko package.


%prep
%setup -q -n suds-jurko-0.6

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1532383111
python3 setup.py build -b py3

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/suds-jurko
cp LICENSE.txt %{buildroot}/usr/share/doc/suds-jurko/LICENSE.txt
python3 -tt setup.py build -b py3 install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(-,root,root,-)
/usr/share/doc/suds-jurko/LICENSE.txt

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
%exclude /usr/lib/python3.7/site-packages/tests/__init__.py
%exclude /usr/lib/python3.7/site-packages/tests/__pycache__/__init__.cpython-37.pyc
/usr/lib/python3*/*
